### PR TITLE
Clarify guix-daemon running instructions

### PR DESCRIPTION
**Pull request by dongcarl**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Unrelated to this change, but for testing windows cross builds in docker, we use `--cap-add` upstream. Not sure if the `--privileged` could be replaced by that.

**Comment by dongcarl** [comment]
> Unrelated to this change, but for testing windows cross builds in docker, we use `--cap-add` upstream. Not sure if the `--privileged` could be replaced by that.

Ah you mean so that we're granting specific capabilities instead of a blanket `--privileged`?

**Comment by MarcoFalke** [comment]
Yeah, not that it matters, but if someone feels like bisecting the capabilities...

**Comment by dongcarl** [comment]
> Yeah, not that it matters, but if someone feels like bisecting the capabilities...

Eh, we'll do it later when it's ready. Good to get it working first before dealing with this. I want to encourage people to run on their own distros anyway.

**Comment by fanquake** [comment]
@dongcarl @MarcoFalke I've opened #5 to track bisecting permissions, which includes my initial attempt at doing that.

**Pull request merged**
